# This compose file should only be used for local development and nothing else.

version: '2'
services:
  # Using this node.js image to mount the local environment inside it and making sure it runs
  web:
    image: node:9.7.1-alpine
    volumes:
      - .:/web
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: [ sh, -c, "cd /web && npm install && cd /web && node node_modules/nodemon/bin/nodemon.js -L --delay 5 release/index.js" ]
    environment:
      PORT: 8080
      DATABASE_URL: postgres://dnazizjfebuydj:02201a6f6b64ac914cebb8fe180d96c32e8917ebb76c4610a9bc328dd8843781@postgres:5432/d9fnnl736pfc5m
    links:
      - "postgres"

  postgres:
    # Production uses 10.0 of Postgres from Heroku but this is fine.
    image: postgres:10.2-alpine
    environment:
      # Come up with some mad testing ones for local testing to really make sure the pipeline works locally
      # as it should. These you cannot typo in place by accident. Impossibru!
      POSTGRES_USER: dnazizjfebuydj
      POSTGRES_PASSWORD: 02201a6f6b64ac914cebb8fe180d96c32e8917ebb76c4610a9bc328dd8843781
      POSTGRES_DB: d9fnnl736pfc5m
    # For debugging purposes, expose the same port for host so we can directly connect to it with our db client
    ports:
      - "5432:5432"


